services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data/db:/data/db
      - ./mongo-data/configdb:/data/configdb

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - ./redis_insight_data:/data
    depends_on:
      - redis